// Generated by CoffeeScript 1.8.0
(function() {
  var Trelloist;

  Trelloist = (function() {
    function Trelloist() {}

    GLOBAL_BOARD;

    Trelloist.prototype.init = function(data, startApp) {
      if (typeof data !== "object") {
        data = {
          appName: data,
          boardId: null
        };
      }
      return Trello.authorize({
        name: data.appName,
        scope: {
          read: true,
          write: true,
          account: true
        },
        expiration: "never",
        success: (function(_this) {
          return function() {
            _this.key = Trello.key();
            _this.token = Trello.token();
            if (data.boardId === null) {
              return startApp(_this);
            } else {
              return _this.loadBoard(data.boardId, startApp);
            }
          };
        })(this),
        error: (function(_this) {
          return function(e) {
            return console.error("We have some problems to login");
          };
        })(this)
      });
    };

    return Trelloist;

  })();

  window.Trelloist = new Trelloist();

}).call(this);
