// Generated by CoffeeScript 1.8.0
(function() {
  var api, getUpdateActions;

  api = require("./Utilites/trelloAPI");

  self.Trello = {};

  self.lastDate;

  self.lastDateSet = false;

  getUpdateActions = function() {
    var API, postParams;
    postParams = {
      filter: "all",
      fields: "all",
      limit: 50
    };
    if (self.lastDateSet) {
      postParams.since = self.lastDate;
    }
    API = new api("/boards/" + self.boardId + "/actions", postParams);
    API.run("GET", (function(_this) {
      return function(actionsData) {
        if (actionsData.length !== 0) {
          if (self.lastDateSet) {
            self.postMessage(actionsData);
          } else {
            self.lastDateSet = true;
          }
          return self.lastDate = actionsData[0].date;
        }
      };
    })(this));
    return setTimeout((function() {
      return getUpdateActions();
    }), 1000);
  };

  self.addEventListener('message', function(e) {
    switch (e.data.cmd) {
      case "start":
        Trello.token = function() {
          return e.data.token;
        };
        Trello.key = function() {
          return e.data.key;
        };
        self.boardId = e.data.boardId;
        return getUpdateActions();
    }
  }, false);

}).call(this);
