// Generated by CoffeeScript 1.8.0
(function() {
  var Board, Globe, List,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Globe = require("./Globe");

  List = require("./List");

  module.exports = Board = (function(_super) {
    __extends(Board, _super);

    function Board(boardData, onReady) {
      Board.__super__.constructor.apply(this, arguments);
      this.id = boardData.id;
      this.name = boardData.name;
      this.lists = [];
      this.members = [];
      this.labels = [];
      this.trelloObj = boardData;
      this.makeReadyLists((function(_this) {
        return function() {
          return onReady(_this);
        };
      })(this));
      this;
    }

    Board.prototype.makeReadyLists = function(onReady) {
      var listData, _i, _len, _ref;
      _ref = this.trelloObj.lists;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        listData = _ref[_i];
        this.lists.push(new List(listData, this.trelloObj));
      }
      return onReady();
    };

    return Board;

  })(Globe);

}).call(this);
