// Generated by CoffeeScript 1.8.0
(function() {
  var Card;

  module.exports = Card = (function() {
    function Card(cardData) {
      this.id = cardData.id;
      this.name = this.text = cardData.name;
      this.desc = cardData.desc;
      this.members = [];
      this.labels = [];
      this.trelloObj = cardData;
    }

    return Card;

  })();

}).call(this);
