// Generated by CoffeeScript 1.8.0
(function() {
  var Card, Globe,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Globe = require("./Globe");

  module.exports = Card = (function(_super) {
    __extends(Card, _super);

    function Card(cardData) {
      this.id = cardData.id;
      this.name = this.text = cardData.name;
      this.desc = cardData.desc;
      this.members = [];
      this.labels = [];
      this.trelloObj = cardData;
    }

    return Card;

  })(Globe);

}).call(this);
