// Generated by CoffeeScript 1.8.0
(function() {
  var Card, Globe, List,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Globe = require("./Globe");

  Card = require("./Card");

  module.exports = List = (function(_super) {
    __extends(List, _super);

    function List(listData, boardData) {
      this.boardData = boardData;
      List.__super__.constructor.apply(this, arguments);
      this.id = listData.id;
      this.name = listData.name;
      this.cards = [];
      this.trelloObj = listData;
      this.makeReadyCards();
      this;
    }

    List.prototype.makeReadyCards = function() {
      var cardData, _i, _len, _ref, _results;
      _ref = this.boardData.cards;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cardData = _ref[_i];
        if (cardData.idList === this.id) {
          _results.push(this.cards.push(new Card(cardData)));
        }
      }
      return _results;
    };

    return List;

  })(Globe);

}).call(this);
