// Generated by CoffeeScript 1.8.0
(function() {
  var Card, List;

  Card = require("./Card");

  module.exports = List = (function() {
    function List(listData, boardData) {
      this.boardData = boardData;
      this.id = listData.id;
      this.name = listData.name;
      this.cards = [];
      this.trelloObj = listData;
      this.makeReadyCards();
      this;
    }

    List.prototype.makeReadyCards = function() {
      var cardData, _i, _len, _ref, _results;
      _ref = this.boardData.cards;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cardData = _ref[_i];
        if (cardData.idList === this.id) {
          _results.push(this.cards.push(new Card(cardData)));
        }
      }
      return _results;
    };

    return List;

  })();

}).call(this);
